project_id = "zsyakwylngqsuxdkdibn"

[functions.summarize-content]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.extract-youtube-transcript]
verify_jwt = false

[functions.get-youtube-captions]
verify_jwt = false

[functions.fetch-url-content]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false
